import Navbar from '../components/Navbar';
import styles from '../styles/Layout.module.css';
import { ReactElement } from 'react';
import Head from 'next/head'

import Footer from './Footer';


interface Props {
    children: ReactElement
}

const Layout = ({ children }: Props) => {
    return (
        <>
            <Head>
                <title>OpenStore.uz</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
            </Head>
            <Navbar />
            <main>{children}</main>
            <Footer />
        </>
    );
};

export default Layout;